version: '3'
services:
  db:
    image: circleci/mysql:8
    ports:
      - '13306:3306'
    restart: always
    environment:
      - MYSQL_DATABASE=cherry_blossom_development
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - .docker/conf.d:/etc/mysql/conf.d
      - .docker/data:/var/lib/mysql
      - .docker/initdb.d:/docker-entrypoint-initdb.d
  web:
    build: .
    ports:
      - '2300:2300'
    tty: true
    stdin_open: true
    working_dir: /srv/
    volumes:
      - .:/srv/
    environment:
      - HANAMI_ENV=development
    command: /bin/sh bin/entrypoint
